pub const LIBAFL_QEMU_COMMAND_START_VIRT : u64 = 0;
pub const LIBAFL_QEMU_COMMAND_START_PHYS : u64 = 1;
pub const LIBAFL_QEMU_COMMAND_INPUT_VIRT : u64 = 2;
pub const LIBAFL_QEMU_COMMAND_INPUT_PHYS : u64 = 3;
pub const LIBAFL_QEMU_COMMAND_END : u64 = 4;
pub const LIBAFL_QEMU_COMMAND_SAVE : u64 = 5;
pub const LIBAFL_QEMU_COMMAND_LOAD : u64 = 6;
pub const LIBAFL_QEMU_COMMAND_VERSION : u64 = 7;
pub const LIBAFL_QEMU_COMMAND_VADDR_FILTER_ALLOW : u64 = 8;


pub const LIBAFL_QEMU_COMMAND_SMM_REPORT_NUM_STREAM : u64 = 9;
pub const LIBAFL_QEMU_COMMAND_SMM_INPUT_STREAM_VIRT : u64 = 10;
pub const LIBAFL_QEMU_COMMAND_SMM_REPORT_DUMMY_MEM : u64 = 11;

pub const LIBAFL_QEMU_COMMAND_SMM_INIT_ENTER : u64 = 12;
pub const LIBAFL_QEMU_COMMAND_SMM_INIT_EXIT : u64 = 13;
pub const LIBAFL_QEMU_COMMAND_SMM_SMI_ENTER : u64 = 14;
pub const LIBAFL_QEMU_COMMAND_SMM_SMI_EXIT : u64 = 15;


pub const LIBAFL_QEMU_COMMAND_SMM_REPORT_SMI_SELECT_INFO : u64  = 16;
pub const LIBAFL_QEMU_COMMAND_SMM_REPORT_COMMBUF_INFO : u64  = 17;
pub const LIBAFL_QEMU_COMMAND_SMM_GET_SMI_SELECT_FUZZ_DATA : u64  = 18;
pub const LIBAFL_QEMU_COMMAND_SMM_GET_COMMBUF_FUZZ_DATA : u64  = 19;
pub const LIBAFL_QEMU_COMMAND_SMM_GET_PCD_FUZZ_DATA : u64 = 20;
pub const LIBAFL_QEMU_COMMAND_SMM_REPORT_HOB_MEM : u64 = 21;
pub const LIBAFL_QEMU_COMMAND_SMM_GET_VARIABLE_FUZZ_DATA : u64 = 22;
pub const LIBAFL_QEMU_COMMAND_SMM_ASK_SKIP_MODULE : u64 = 23;
pub const LIBAFL_QEMU_COMMAND_SMM_GET_SMI_GROUP_INDEX_FUZZ_DATA : u64 = 24;
pub const LIBAFL_QEMU_COMMAND_SMM_REPORT_SMM_MODULE_INFO : u64 = 25;

pub const LIBAFL_QEMU_COMMAND_SMM_REPORT_SMM_FUZZ_GROUP : u64 = 26;
pub const LIBAFL_QEMU_COMMAND_SMM_GET_EXEC_CMD : u64 = 27;
pub const LIBAFL_QEMU_COMMAND_SMM_GET_FUZZ_SMI_INDEX : u64 = 28;
pub const LIBAFL_QEMU_COMMAND_SMM_REPORT_SMI_INFO : u64 = 29;

pub const LIBAFL_QEMU_COMMAND_SMM_REPORT_SKIP_MODULE_INFO : u64 = 30;
pub const LIBAFL_QEMU_COMMAND_SMM_REPORT_UNLOAD_MODULE_INFO : u64 = 31;

pub const LIBAFL_QEMU_END_UNKNOWN : u64 = 0;
pub const LIBAFL_QEMU_END_OK : u64  = 1;
pub const LIBAFL_QEMU_END_CRASH : u64  = 2;
pub const LIBAFL_QEMU_END_SMM_INIT_START : u64  = 3;
pub const LIBAFL_QEMU_END_SMM_INIT_END : u64  = 4;
pub const LIBAFL_QEMU_END_SMM_MODULE_START : u64 = 5;
pub const LIBAFL_QEMU_END_SMM_FUZZ_START : u64  = 6;
pub const LIBAFL_QEMU_END_SMM_FUZZ_END : u64  = 7;
pub const LIBAFL_QEMU_END_SMM_INIT_UNSUPPORT : u64 = 8;
pub const LIBAFL_QEMU_END_SMM_ASSERT : u64 = 9;


pub const SMM_FUZZ_RUN : u64 = 0;
pub const SMM_FUZZ_REPORT : u64 = 1;
pub const SMM_FUZZ_BREAK : u64 = 2;